server:
   port: 8888 
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: "file:///C:/Tarun/STS Workspace/microservice/config-server/git-local-config-repository"
          #default-label: master
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 
logging:
    level:
      org:
        springframework:
          cloud:
            config: INFO
          boot: INFO